apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-service
  title: Checkout Service
  description: Handles payment and cart operations.
  annotations:
    backstage.io/techdocs-ref: dir:./docs # Assuming docs are in a 'docs' sub-directory
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
spec:
  type: service
  owner: group:default/payments # Assigning to a specific team/group
  system: checkout-system # Ensure 'checkout-system' exists as a Backstage System entity
  lifecycle: production
