apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-service
  title: Checkout Service
  description: Handles payment and cart
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: devops
  system: checkout-system
